default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: encore_rader_development

test:
  <<: *default
  database: encore_rader_test

production:
  <<: *default
  database: encore_rader_production
  username: encore
  password: <%= ENV['ENCORE_DATABASE_PASSWORD'] %>
